name = "GaussianBasisKernels"
uuid = "aa7a2209-7a51-48b2-9f84-4fb7a35f78a5"
authors = ["Christoph Ortner <christophortner0@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
